version: "3"

services:
  dbt:
    build: ${PWD}/.
    image: dbt_blogs
    container_name: dbt_blogs
    env_file:
      - ${PWD}/.env
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/dbt_project:/home/dbt_user/dbt_project
    networks:
      - default
      - postgres_bridge
    tty: true

networks:
  default: null

  postgres_bridge:
    external:
      name: postgres_bridge
