version: "3"

services:
  dbt:
    build: ${PWD}/dbt/Dockerfile
    image: dbt_blogs
    container_name: dbt_blogs
    env_file:
      - ${PWD}/.env
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/dbt:/home/dbt_user/dbt_project
    tty: true

  postgres:
    build: ${PWD}/postgres/Dockerfile
    image: reddit_postgres
    container_name: reddit_postgres
    env_file:
      - ${PWD}/.env
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - ${PWD}/postgres/reddit_postgres:/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
