version: "3"

services:
  postgres:
    volumes:
      - ${PWD}/postgres/postgres-prod.conf:/etc/postgresql/postgresql.conf
      - redditpgdata:/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  redditpgdata:
    external:
      name: redditpgdata
