version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - checkout
      - restore_cache:
          key: poetry-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: Check poetry lock file
          command: |
            make install-poetry
            make check-poetry
      - run:
          name: install poetry dependencies
          command: |
            make install-poetry
            make requirements
      - save_cache:
          key: poetry-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - .venv
             - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: lint python
          command: |
            ls -la
            make lint-python
      - run:
          name: lint sql
          command: | 
            ls -la dbt/dbt_project 
            make lint-sql
