version: 2
jobs:
  build:
    docker:
      - image: python:3.9.6
    steps:
      - checkout
      - restore_cache:
          key: poetry-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: Update poetry requirements
          command: make update-poetry
      - save_cache:
          key: poetry-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - .venv
      - run:
          name: linting
          command: make lint-python
      - run:
          name: lint sql
          command: make lint-sql

